/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file was added after baseline commit
 * 79d38f666336141d962109a864a6744bf66e438c and is licensed under
 * LGPL-3.0-only by its respective copyright holder.
 * See LICENSE and LICENSING.md.
 */

/* Generated by scripts/gen_aux_assets.py — DO NOT EDIT. */
#pragma once

#include <stddef.h>
#include <stdint.h>

/* One precompiled aux shader asset. data/size are the embedded
 * metallib bytes; hash is their FNV-1a-64 fingerprint, validated at
 * load time against a runtime recomputation. */
typedef struct MGLAuxShaderAsset {
    const char *name;
    const unsigned char *data;
    size_t size;
    uint64_t hash;
    const char *functions[4];
} MGLAuxShaderAsset;

const MGLAuxShaderAsset *mglAuxShaderAssetFind(const char *name);
extern const MGLAuxShaderAsset mglAuxShaderAssets[];
extern const size_t mglAuxShaderAssetCount;

/* FNV-1a-64 used by both the generator and the runtime verifier. */
static inline uint64_t mglAuxAssetHash(const unsigned char *bytes, size_t size) {
    uint64_t h = UINT64_C(0xCBF29CE484222325);
    for (size_t i = 0; i < size; ++i) { h ^= bytes[i]; h *= UINT64_C(0x100000001B3); }
    return h;
}
