#!/usr/bin/env python3
"""Generate the read-only aux shader asset table from precompiled metallibs.

Inputs:
  argv[1]  manifest (MGL/aux_shaders/MANIFEST): asset_name|source|entries
  argv[2]  directory containing <source-base>.metallib files
  argv[3]  output header path (mgl_aux_assets.h)
  argv[4]  output C source path (mgl_aux_assets.c)

Each asset row embeds the metallib bytes, its FNV-1a-64 fingerprint, and the
entry function names.  The runtime may only consume these embedded bytes; it
never reads .metal sources or paths.  Regenerate with `make` whenever a
*.metal changes; both outputs are committed so builds share one table.
"""
import hashlib
import sys

FNV1A64_OFFSET = 0xCBF29CE484222325
FNV1A64_PRIME = 0x100000001B3


def fnv1a64(data: bytes) -> int:
    h = FNV1A64_OFFSET
    for b in data:
        h ^= b
        h = (h * FNV1A64_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def parse_manifest(path: str):
    assets = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("|")
            assert len(parts) == 3, f"bad MANIFEST line: {line}"
            name, source, entries = parts
            funcs = [e for e in entries.split(",") if e]
            assert funcs, f"no entry functions for {name}"
            assets.append((name, source, funcs))
    return assets


def emit_protected(name: str, data: bytes) -> str:
    """Emit a 'static const unsigned char' byte array enclosed in a linkage
    scope so multiple generated includes stay collision-free yet the table
    keeps static storage."""
    lines = []
    lines.append("static const unsigned char s_%s[%d] = {" % (name, len(data)))
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 5:
        print("usage: gen_aux_assets.py MANIFEST METALLIB_DIR OUT_H OUT_C",
              file=sys.stderr)
        return 2
    manifest_path, metallib_dir, out_h, out_c = sys.argv[1:]

    assets = parse_manifest(manifest_path)
    rows = []
    for name, source, funcs in assets:
        base = source[:-len(".metal")] if source.endswith(".metal") else source
        with open(f"{metallib_dir}/{base}.metallib", "rb") as fh:
            data = fh.read()
        assert data, f"empty metallib for {name}"
        rows.append((name, data, funcs))

    header = [
        "/*",
        " * SPDX-License-Identifier: LGPL-3.0-only",
        " *",
        " * This file was added after baseline commit",
        " * 79d38f666336141d962109a864a6744bf66e438c and is licensed under",
        " * LGPL-3.0-only by its respective copyright holder.",
        " * See LICENSE and LICENSING.md.",
        " */",
        "",
        "/* Generated by scripts/gen_aux_assets.py — DO NOT EDIT. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* One precompiled aux shader asset. data/size are the embedded",
        " * metallib bytes; hash is their FNV-1a-64 fingerprint, validated at",
        " * load time against a runtime recomputation. */",
        "typedef struct MGLAuxShaderAsset {",
        "    const char *name;",
        "    const unsigned char *data;",
        "    size_t size;",
        "    uint64_t hash;",
        "    const char *functions[4];",
        "} MGLAuxShaderAsset;",
        "",
        "const MGLAuxShaderAsset *mglAuxShaderAssetFind(const char *name);",
        "extern const MGLAuxShaderAsset mglAuxShaderAssets[];",
        "extern const size_t mglAuxShaderAssetCount;",
        "",
        "/* FNV-1a-64 used by both the generator and the runtime verifier. */",
        "static inline uint64_t mglAuxAssetHash(const unsigned char *bytes, size_t size) {",
        "    uint64_t h = UINT64_C(0xCBF29CE484222325);",
        "    for (size_t i = 0; i < size; ++i) { h ^= bytes[i]; h *= UINT64_C(0x100000001B3); }",
        "    return h;",
        "}",
        "",
    ]

    arrays = []
    table = ["const MGLAuxShaderAsset mglAuxShaderAssets[] = {"]
    for name, data, funcs in rows:
        arrays.append(emit_protected(name, data))
        func_literals = ", ".join('"%s"' % f for f in funcs)
        func_fill = func_literals + ", NULL" * (4 - len(funcs))
        table.append(
            '    { "%s", s_%s, sizeof(s_%s), UINT64_C(0x%016x), { %s } },'
            % (name, name, name, fnv1a64(data), func_fill)
        )
    table.append("};")
    table.append("const size_t mglAuxShaderAssetCount ="
                 " sizeof(mglAuxShaderAssets) / sizeof(mglAuxShaderAssets[0]);")
    table.append("")
    table.append("const MGLAuxShaderAsset *mglAuxShaderAssetFind(const char *name) {")
    table.append("    if (!name) return NULL;")
    table.append("    for (size_t i = 0; i < mglAuxShaderAssetCount; ++i) {")
    table.append("        if (mglAuxShaderAssets[i].name[0] == name[0] &&"
                 " __builtin_strcmp(mglAuxShaderAssets[i].name, name) == 0) {")
    table.append("            return &mglAuxShaderAssets[i];")
    table.append("        }")
    table.append("    }")
    table.append("    return NULL;")
    table.append("}")

    c_body = [
        "/*",
        " * SPDX-License-Identifier: LGPL-3.0-only",
        " *",
        " * This file was added after baseline commit",
        " * 79d38f666336141d962109a864a6744bf66e438c and is licensed under",
        " * LGPL-3.0-only by its respective copyright holder.",
        " * See LICENSE and LICENSING.md.",
        " */",
        "",
        "/* Generated by scripts/gen_aux_assets.py — DO NOT EDIT. */",
        '',
        '#include "mgl_aux_assets.h"',
        "#include <stddef.h>",
        "",
    ]
    c_body.extend(arrays)
    c_body.append("")
    c_body.extend(table)
    c_body.append("")

    with open(out_h, "w", encoding="utf-8") as fh:
        fh.write("\n".join(header))
    with open(out_c, "w", encoding="utf-8") as fh:
        fh.write("\n".join(c_body))

    for name, data, _funcs in rows:
        print(f"asset {name}: {len(data)} bytes fnv1a64=0x{fnv1a64(data):016x}")
    print(f"wrote {out_h} and {out_c} ({len(rows)} assets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
